name: 'GDBP: Start AWS CodeBuild Project via Lambda Function'
description: 'Invokes an AWS Lambda function that starts and returns the ID of an AWS CodeBuild project, streaming the build logs back to Github.'
inputs:
  env-vars-for-codebuild:
    description: 'Comma separated list of environment variables to send to CodeBuild'
    required: false
outputs:
  aws-build-id:
    description: 'The AWS CodeBuild Build ID for this build.'
runs:
  using: 'node12'
  main: 'dist/index.js'
